import { Committee, Milestone, DailySubmission, DashboardSummary, Task } from '@/types';

export const mockCommittees: Committee[] = [
  {
    id: '1',
    name: 'Logistics & Venue',
    description: 'Responsible for venue booking, catering, transportation, and on-site logistics.',
    lead_name: 'Sarah Jenkins',
    lead_email: 'sarah@event.com',
    status: 'on_track',
    progress_pct: 82,
    member_count: 8,
    submission_streak: 12,
    last_submitted_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Marketing & PR',
    description: 'Handles social media campaigns, press releases, speaker announcements, and branding.',
    lead_name: 'David Chen',
    lead_email: 'david@event.com',
    status: 'stalled',
    progress_pct: 45,
    member_count: 6,
    submission_streak: 0,
    last_submitted_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Tech & AV Services',
    description: 'Manages all technical infrastructure, A/V equipment, streaming, and IT support.',
    lead_name: 'Maya Patel',
    lead_email: 'maya@event.com',
    status: 'critical',
    progress_pct: 12,
    member_count: 5,
    submission_streak: 0,
    last_submitted_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Finance & Sponsorship',
    description: 'Manages budgets, invoices, sponsor relations, and financial reporting.',
    lead_name: 'James Okonkwo',
    lead_email: 'james@event.com',
    status: 'at_risk',
    progress_pct: 58,
    member_count: 4,
    submission_streak: 5,
    last_submitted_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Programming & Speakers',
    description: 'Curates the event agenda, manages speaker invitations and schedules.',
    lead_name: 'Aisha Rahman',
    lead_email: 'aisha@event.com',
    status: 'on_track',
    progress_pct: 76,
    member_count: 7,
    submission_streak: 9,
    last_submitted_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Volunteer Coordination',
    description: 'Recruits and manages volunteers for the event day.',
    lead_name: 'Tom Bradley',
    lead_email: 'tom@event.com',
    status: 'on_track',
    progress_pct: 91,
    member_count: 12,
    submission_streak: 15,
    last_submitted_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    created_at: '2026-06-01T00:00:00Z',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: '1',
    title: 'Venue Booking Confirmation',
    description: 'Final contract signed, deposit paid, and floor plan approved by all stakeholders.',
    deadline: '2026-07-15',
    committee_id: '1',
    committee: mockCommittees[0],
    weight: 25,
    status: 'at_risk',
    progress_pct: 45,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Keynote Speaker Contracts',
    description: 'All 5 keynote speakers confirmed, travel booked, and NDAs signed.',
    deadline: '2026-07-22',
    committee_id: '5',
    committee: mockCommittees[4],
    weight: 15,
    status: 'in_progress',
    progress_pct: 80,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Early Bird Marketing Launch',
    description: 'Launch all early bird registration campaigns across social and email.',
    deadline: '2026-08-01',
    committee_id: '2',
    committee: mockCommittees[1],
    weight: 20,
    status: 'in_progress',
    progress_pct: 35,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '4',
    title: 'Initial Budget Approval',
    description: 'Full event budget reviewed and signed off by board.',
    deadline: '2026-06-10',
    committee_id: '4',
    committee: mockCommittees[3],
    weight: 10,
    status: 'completed',
    progress_pct: 100,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'AV Equipment Procurement',
    description: 'All audio-visual equipment ordered and delivery confirmed.',
    deadline: '2026-07-30',
    committee_id: '3',
    committee: mockCommittees[2],
    weight: 18,
    status: 'at_risk',
    progress_pct: 15,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '6',
    title: 'Volunteer Onboarding Complete',
    description: 'All 80 volunteers briefed, trained, and assigned to stations.',
    deadline: '2026-09-01',
    committee_id: '6',
    committee: mockCommittees[5],
    weight: 12,
    status: 'in_progress',
    progress_pct: 60,
    created_at: '2026-06-01T00:00:00Z',
  },
];

export const mockSubmissions: DailySubmission[] = [
  {
    id: '1',
    committee_id: '1',
    committee: mockCommittees[0],
    submission_date: new Date().toISOString().split('T')[0],
    summary: 'Finalized CAD floor plan for Exhibition Hall B. Met with catering vendor Apex Foods – selected the premium buffet package at ₹850/head. Security deposit of ₹150,000 transferred to venue management. Next step: finalize parking arrangements for 300+ attendees.',
    files: [
      { name: 'hall_b_v3_final.pdf', url: '#', type: 'application/pdf', size: 2400000 },
      { name: 'catering_quote_apex.xlsx', url: '#', type: 'application/xlsx', size: 145000 },
    ],
    llm_analysis: {
      progress_pct: 82,
      completed_tasks: ['Floor plan finalized', 'Catering vendor selected', 'Security deposit paid'],
      blockers: ['Parking arrangement pending', 'Accessibility audit not yet scheduled'],
      sentiment: 'positive',
      key_metrics: { 'Vendors confirmed': '3/4', 'Budget spent': '45%', 'Days to deadline': '19' },
      overall_assessment: 'Logistics committee is on track with strong progress today. Immediate attention needed for parking logistics to avoid timeline slippage.',
      analyzed_at: new Date().toISOString(),
    },
    submitted_by: 'sarah@event.com',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    committee_id: '5',
    committee: mockCommittees[4],
    submission_date: new Date().toISOString().split('T')[0],
    summary: 'Confirmed 4 out of 5 keynote speakers. Dr. Ananya Krishnan signed NDA and submitted bio. Still awaiting contract from international speaker Marcus Webb due to timezone difference. Workshop schedule draft completed and sent for review.',
    files: [
      { name: 'schedule_draft_v2.pdf', url: '#', type: 'application/pdf', size: 890000 },
    ],
    llm_analysis: {
      progress_pct: 76,
      completed_tasks: ['4/5 speakers confirmed', 'Workshop schedule drafted', 'Bio submissions received'],
      blockers: ['Marcus Webb contract pending (international timezone delay)'],
      sentiment: 'positive',
      key_metrics: { 'Speakers confirmed': '4/5', 'Workshops planned': '12', 'Schedule completion': '80%' },
      overall_assessment: 'Programming committee performing well. One minor blocker with international speaker but overall trajectory is strong.',
      analyzed_at: new Date().toISOString(),
    },
    submitted_by: 'aisha@event.com',
    created_at: new Date().toISOString(),
  },
];

export const mockTasks: Task[] = [
  { id: '1', title: 'Confirm speaker list for promotional materials', milestone_id: '3', milestone_title: 'Phase 2 Asset Creation', completed: false },
  { id: '2', title: 'Design initial poster concepts', milestone_id: '2', milestone_title: 'Core Branding Sign-off', completed: true },
  { id: '3', title: 'Draft social media copy for early bird launch', milestone_id: '3', milestone_title: 'Early Bird Campaign', completed: false },
  { id: '4', title: 'Set up email campaign in Mailchimp', milestone_id: '3', milestone_title: 'Early Bird Campaign', completed: false },
  { id: '5', title: 'Coordinate with Logistics for venue photos', milestone_id: '2', milestone_title: 'Core Branding Sign-off', completed: true },
];

export const mockDashboard: DashboardSummary = {
  overall_progress: 72,
  days_to_event: 81,
  total_committees: 6,
  active_committees: 6,
  active_blockers: 3,
  total_submissions_today: 4,
  committees_submitted_today: 4,
  overdue_milestones: 2,
  ai_brief: 'Overall event progress is tracking at 72%, with Logistics and Programming marking key milestones today. However, the Tech & AV committee has flagged critical delays — only 12% complete with an overdue submission 3 days ago. Finance has 3 active blockers related to budget approvals that require immediate coordinator attention. With 81 days remaining, the highest priority risk is the AV Services procurement gap which could cascade into technical setup delays closer to event day.',
  committee_progress: mockCommittees.map(c => ({
    id: c.id,
    name: c.name,
    progress_pct: c.progress_pct,
    status: c.status,
    last_submitted_at: c.last_submitted_at,
  })),
};

// Historical sparkline data per committee
export const mockSparklineData: Record<string, number[]> = {
  '1': [60, 65, 68, 70, 72, 75, 78, 80, 82],
  '2': [30, 35, 38, 40, 42, 43, 44, 44, 45],
  '3': [10, 11, 11, 12, 11, 12, 12, 11, 12],
  '4': [40, 45, 48, 50, 52, 55, 56, 57, 58],
  '5': [55, 60, 63, 66, 68, 70, 72, 74, 76],
  '6': [70, 74, 78, 82, 84, 86, 88, 90, 91],
};
